name: 'Poetry action'
author: 'Barnaby Gray'
description: 'Install poetry, and your dependencies'
inputs:
  poetry-version:
    description: 'poetry version'
    required: false
    default: '1.1.5'
runs:
  using: "composite"
  steps:
    - name: Install poetry
      shell: bash
      run: |
        pip install poetry==${{ inputs.poetry-version }}
        poetry config virtualenvs.create true
        poetry config cache-dir ~/.poetry
        poetry config virtualenvs.path ~/.poetry/venv

    - name: Cache poetry virtualenv
      uses: actions/cache@v2
      id: poetry-cache
      with:
        path: ~/.poetry/venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: poetry install
      shell: bash
